# Generated by Django 5.0.6 on 2024-06-19 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Telegram Group',
                'verbose_name_plural': 'Telegram Groups',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='is accepted')),
                ('is_enter_group', models.BooleanField(default=False, verbose_name='is enter group')),
                ('enter_group_date', models.DateTimeField(blank=True, null=True, verbose_name='enter group date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CustomUser')),
            ],
            options={
                'verbose_name': 'Applications',
                'verbose_name_plural': 'Applicationss',
            },
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='managefy.applications', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'AdminMessage',
                'verbose_name_plural': 'AdminMessages',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_whom', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('all', 'All')], max_length=255, verbose_name='for whom')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='managefy.courses', verbose_name='Course')),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organised_groups', to=settings.AUTH_USER_MODEL, verbose_name='Organiser')),
                ('telegram_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='managefy.telegramgroups', verbose_name='Telegram Group')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.AddField(
            model_name='applications',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managefy.groups', verbose_name='Group'),
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='managefy.applications', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'UserMessage',
                'verbose_name_plural': 'UserMessages',
            },
        ),
    ]
